# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd01b7702939d60b8d9c200e908d54220d1b8e64bbce4270fe4aeea437dde1e2d2d7c145457b717082972ad785fd6e3e0d3514ab211c4212c4e9d2efa146f4a9

test:
  secret_key_base: 592555452f4c8e6dc4353b1f23ece3249c83e0fc27c0cd4cf380f3eacaaad482cfb04d9e9566451423e9b2a1262eb7461dafad977ac16caae5e560cab0765710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
